# Generated by Django 4.1.1 on 2022-09-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_buy_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buy_Stock',
            new_name='Trade',
        ),
    ]
