# Generated by Django 4.1.1 on 2022-09-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_rename_buy_stock_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='qty',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
